[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["corepack enable", "corepack prepare pnpm@latest --activate", "pnpm install"]

[phases.build]
cmd = "pnpm run build"

[start]
cmd = "pnpm start"