[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@10.15.0 --activate",
  "pnpm install"
]

[phases.build]
cmd = "pnpm run build"

[start]
cmd = "pnpm start"
